apiVersion: v1
kind: Service
metadata:
  name: smmarketvalue-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-2:398646198502:certificate/a603e405-923d-4260-a31b-fdb72e0565cc
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  selector:
    app: smmarketvalue
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
